### ISSUE TITLE
s->cur_file_info.compression_method response 99

### ISSUE THREAD

**Issue by shijian910411** [abbeycode/UnzipKit#105]
hi

Compress zip with WinRAR and set password, return Error opening archive （103） 
s->cur_file_info.compression_method response 99。
What do I need to do to work properly

thanks

**Comment by abbeycode** [comment]
Hey, sorry I didn't respond earlier. In case you didn't come to a resolution yet, I think you're going to want to use a library for decompressing RAR archives. UnzipKit is for ZIP format archives. I can recommend my own [UnrarKit](https://github.com/abbeycode/UnrarKit) library. Please try that and let me know if that works for you.
