### ISSUE TITLE
Unable to extract Zip folder contents if zip has password

### ISSUE THREAD

**Issue by SravanPeddi** [abbeycode/UnzipKit#111]
Hi Team,

Unable to unzip files in zip folder if zip having password.
Used following snippet to extract.
   
 NSError *archiveError = nil;
    UZKArchive *archive = [[UZKArchive alloc] initWithPath:zipPath password:@"12345" error:&archiveError];

    BOOL extractFilesSuccessful = [archive extractFilesTo:[self getDocumentsPath] overwrite:YES error:&error]; 

Here extractFilesSuccessful  is giving as NO.
Note: I am able to extract zip folder which is not having password.

How to extract zip which has password .

**Comment by abbeycode** [comment]
I'm going to close this one as a duplicate of #110, as I believe it's most likely the same underlying problem.
