### ISSUE TITLE
isPasswordProtected is not always correct

### ISSUE THREAD

**Issue by pieterclaerhout** [abbeycode/UnzipKit#13]
From what I see in the code, only the first file is checked to see if the zip file is password protected.

However, if I'm not mistaking, the encryption flag is file specific, so if the first file is not using a password, you will get the incorrect result.

Any idea what would be the best way to fix this?

**Comment by abbeycode** [comment]
That's a good point - that method should return YES if any file has a password. I'll incorporate that into the next release.

**Comment by abbeycode** [comment]
I made a fix in [issue13](https://github.com/abbeycode/UnzipKit/tree/issue13) branch. Take a look and let me know if that works for you!

**Comment by pieterclaerhout** [comment]
Cool, works like a charm now! Thanks.

**Comment by abbeycode** [comment]
This fix has been released in v1.4, now live on CocoaPods
