### ISSUE TITLE
Allow password-protection for streamed files when CRC is known up front

### ISSUE THREAD

**Issue by abbeycode** [abbeycode/UnzipKit#16]
1. Add a `-writeIntoBuffer` overload that takes a CRC argument. If given, allow password protection
2. After writing the buffered data, verify the calculated CRC matches the argument given, and return an error (with a new error code) if it doesn't

Suggested by @SkiesOFF in comments on issue #9

**Comment by abbeycode** [comment]
@SkiesOFF, take a look at the overloads in master, and let me know if it works for you.

**Comment by SkiesOFF** [comment]
I will take a look as soon as possible, thank you!

**Comment by SkiesOFF** [comment]
Yes, very good, thank you.

Just a little detail:

```objective-c
- (BOOL)writeIntoBuffer:(NSString *)filePath
               fileDate:(NSDate *)fileDate
      compressionMethod:(UZKCompressionMethod)method
              overwrite:(BOOL)overwrite
                    CRC:(uLong)preCRC
                  error:(NSError *__autoreleasing *)error
                  block:(BOOL (^)(BOOL (^)(const void *, unsigned int), NSError *__autoreleasing *))action
{
    return [self writeIntoBuffer:filePath
                        fileDate:fileDate
               compressionMethod:method
                       overwrite:YES
                             CRC:preCRC
                        password:nil
                           error:error
                           block:action];
}
```

overwrite is not passing the correct parameter here.

**Comment by abbeycode** [comment]
@SkiesOFF Thanks! Good catch! Should be better now. This will be included in the next release.

**Comment by abbeycode** [comment]
I released this to CocoaPods
