### ISSUE TITLE
High memory usage when writing many files in archive

### ISSUE THREAD

**Issue by SkiesOFF** [abbeycode/UnzipKit#18]
Try compressing this whole folder (buffered or NSData) and your app is going to crash because of high memory usage.

Files used: https://www.dropbox.com/s/ztyk5t9u4jvedy4/largeZipFile.zip?dl=0
(20mb - 3500 files)

When i tried to compress the folder above, i made a for loop and for each file i used writeData or writeIntoBuffer. --Memory usage grows very fast and soon crashes the app.

**Method to look:**

```objective-c
- (BOOL)performWriteAction:(int(^)(uLong *crc, NSError * __autoreleasing*innerError))write
                  filePath:(NSString *)filePath
                  fileDate:(NSDate *)fileDate
         compressionMethod:(UZKCompressionMethod)method
                  password:(NSString *)password
                 overwrite:(BOOL)overwrite
                       CRC:(uLong)crc
                     error:(NSError * __autoreleasing*)error
```

**The Problem:**

If overwrite is YES, UnzipKit will verify if a file with the same name exists inside the archive and delete it. This consumes a lot of memory since the archive has many files. This memory should be released as soon as possible, when it is not needed anymore. 

Since i'm writing many files and the memory will only be released when i finish all the files, the memory will only grow by time, eventually crashing the app.

**Fix:**

```objective-c
    if (overwrite) {
        @autoreleasepool {
            NSError *listFilesError = nil;
            NSArray *existingFiles = [self listFileInfo:&listFilesError];
            
            if (existingFiles) {
                NSIndexSet *matchingFiles = [existingFiles indexesOfObjectsPassingTest:
                                             ^BOOL(UZKFileInfo *info, NSUInteger idx, BOOL *stop) {
                                                 if ([info.filename isEqualToString:filePath]) {
                                                     *stop = YES;
                                                     return YES;
                                                 }
                                                 
                                                 return NO;
                                             }];
                
                if (matchingFiles.count > 0 && ![self deleteFile:filePath error:error]) {
                    NSLog(@"Failed to delete %@ before writing new data for it", filePath);
                    return NO;
                }
            }
        }
    }
```

**Comment by abbeycode** [comment]
Thanks, I'll take a look - would you consider making a pull request? I can walk you through it if you're not familiar with the process.

**Comment by abbeycode** [comment]
I've been looking into ways to improve memory consumption, and I'll let you know when I come up with something. I want to make sure I point out to you, though, that you can turn `overwrite` off, if you know it's not necessary for your application. If you're writing a directory of files for instance, you know none of them will have the same names, and you won't be writing any files twice. I'm not sure the details of what you're doing, but it should definitely speed it up for you and improve memory usage.

**Comment by SkiesOFF** [comment]
Yes, i did turn overwrite off first but i was curious to see why this was happening. I could insert an autoreleasepoll in my for loop too, but i think its best to release this memory as soon as possible (not everyone knows about autoreleasepol, so they may have this problem).

**Comment by abbeycode** [comment]
Check out the [issue18](https://github.com/abbeycode/UnzipKit/tree/issue18) branch - I performed a few different optimizations, including wrapping one of the lines you mentioned in an `@autoreleasepool`. The best solution would probably be to use a `struct` instead of a `class` for `UZKFileInfo`, but C structs don't have calculated properties (which would undo one of my optimizations) and Swift structs can't be used from Objective-C. At some point, if the library goes Swift-only, that would probably be a way around using the autorelease pool.

**Comment by abbeycode** [comment]
If this works for you, I can merge into master and make a new CocoaPods release

**Comment by abbeycode** [comment]
I released this to CocoaPods
