### ISSUE TITLE
Nullable passwords

### ISSUE THREAD

**Issue by mohpor** [abbeycode/UnzipKit#34]
Hi,

The `password` parameter in `initWithPath:password:error` method (and I'm guessing a few other methods like that) is implicitly assigned  the NONNull attribute (because they are inside the `NS_ASSUME_NONNULL_BEGIN ... NS_ASSUME_NONNULL_END` block). But password is a nullable parameter indeed. An empty string results in error. 
I suggest either assigning nullable attribute to parameters and objects that should be nullable, or remove the assume block and assign all parameters the proper attribute (not recommended).

Regards
Mohammad

P.S.: setting password here as nil won't generate error, but will generate warnings.

**Comment by abbeycode** [comment]
This has been addressed in v1.7.2 of UnzipKit, which is now live on CocoaPods.
