### ISSUE TITLE
Add module map to project

### ISSUE THREAD

**Issue by amosavian** [abbeycode/UnzipKit#41]
This will allow adding files to project and treat them as framework in swift projects, without bridging header by adding `.modulemap` file to `Swift Compiler -Search Path -> Import Paths`.

You can also consider for UnrarKit.

**Comment by abbeycode** [comment]
As always, thanks for the input!

Isn't the module map meant for bringing C libraries into Swift, though? Do you have examples of other Objective-C libraries offering modulemap files for this purpose?

**Comment by amosavian** [comment]
Maybe you are right. I didn't test for objc.
