### ISSUE TITLE
Error #104 when unzipping file

### ISSUE THREAD

**Issue by amosavian** [abbeycode/UnzipKit#43]
Hi,
Please test this file, I get an error related to Minizip, while this file seems okay in other unarchivers.

https://subscene.com/subtitle/download?mac=EDZqbNIgfeS9cyBP9x-cmJBnQQo-bF2uuBKvYcRRpQmrhb40MLC6PggLrUjQw01FOZuq_OUp9ye8fKcA72BIJJoJnmpVgj3yIthwQo0eEQ1aph_jwKXCwT7s6CXnykT40

**Comment by abbeycode** [comment]
I'll take a look when I can. Have you tried stepping through, though, to see when the error originates? That's been the most helpful step for me in the past.

Also, could you attach the archive itself to the issue?

**Comment by amosavian** [comment]
Hey @abbeycode ,
Unfortunately I can't reproduce the error 😞
