### ISSUE TITLE
Crash when using wrong password to open encrypted zip file

### ISSUE THREAD

**Issue by monobono** [abbeycode/UnzipKit#51]
```
NSError *error = nil;

UZKArchive *archive = [[UZKArchive alloc] initWithURL:pathURL password:@"wrongPW" error:&error];

if(![archive validatePassword]) {
}
```

leads to crash

**Comment by abbeycode** [comment]
Hey, thanks for reaching out. I tried reproducing the crash in a test case (which I pushed to a new branch named `issue51`), but it passes. Can you try modifying that test case so it fails, demonstrating your crash? Also, is this happening for Mac or iOS (and, if iOS, device or simulator)?

**Comment by abbeycode** [comment]
Is this still a problem for you?

**Comment by segunlee** [comment]
i got same issue,

![ohno](https://user-images.githubusercontent.com/3186834/27019357-e9ade2a8-4f72-11e7-8c43-97b3f0fc49c3.png)

**Comment by abbeycode** [comment]
@segunlee Thanks for letting me know! Can you help me reproduce this? If possible, could you send me the archive you're having trouble with, and your code that's causing the crash? I have test cases for incorrect passwords, and they don't crash.

**Comment by abbeycode** [comment]
@monobono @segunlee Are either of you able to help me reproduce this in a test case? You can checkout the `issue51` branch, which has a test case named `testValidatePassword_Issue51` I created to help get you started.

**Comment by amosavian** [comment]
@abbeycode I described how to resolve problem in #56. Just amend your code with my diff 😃

**Comment by abbeycode** [comment]
@amosavian I'm going through open issues now, so you'll see me replying to a bunch of them. Sorry to hit you all at once :)

Regarding this one, I see what you proposed in issue #56, but as I just commented there, I would like to have a test case that fails, demonstrating the bug. As I did with the other one, I created an [issue51 branch](https://github.com/abbeycode/UnzipKit/tree/issue51) in which I attempted to reproduce the issue, but the test passes. Can you, @segunlee or @monobono please modify it to reproduce this bug? If not, I'll have to close the issue out.

**Comment by amosavian** [comment]
@abbeycode to create test case as I suggested in #56, You must have a file bigger than 4096 bytes (size of a chunk) in a password encrypted archive.

**Comment by abbeycode** [comment]
I somehow missed the 4096 byte comment back then. That's probably all I need to continue on it. Thanks! I'll let you know how it goes and if I have any other questions.

**Comment by amosavian** [comment]
Thanks in advance ❤️❤️❤️

**Comment by abbeycode** [comment]
I was able to reproduce, and fix. Look for it in the first v1.9 beta!
