### ISSUE TITLE
Update Cocoapods trunk automatically

### ISSUE THREAD

**Issue by amosavian** [abbeycode/UnzipKit#52]
Please see what I've done:

https://github.com/amosavian/FileProvider/blob/master/.travis.yml

<img width="924" alt="screen shot 1395-11-26 at 11 15 26 pm" src="https://cloud.githubusercontent.com/assets/6725192/22946056/8bc95924-f30b-11e6-9142-1e606e0b2e46.png">

**Comment by abbeycode** [comment]
I already have automatic CocoaPods integration - have you seen the way I do it? I push all builds tagged with a version number.

**Comment by amosavian** [comment]
I see tnx.
