### ISSUE TITLE
fileSystemRepresentation instead of UTF8String

### ISSUE THREAD

**Issue by amosavian** [abbeycode/UnzipKit#53]
Please check https://github.com/ZipArchive/ZipArchive/issues/326 and the link to blog inside issue.

**Comment by abbeycode** [comment]
Good call! I'll take a look at this when I can (feel free to jump in, if you're able). I think a good first step would be to see if we can manufacture a unit test that verifies this is a problem. Ideally, it would explicitly create an HFS+ image, and an APFS image, running a test on each. We can use that to (a) verify this is definitely a problem, and (b) to verify the fix.

Each test (`ifdef`'ed for running on macOS 10.12) should basically:

1. Create and mount a sparse disk image of the target format (either HFS+ or APFS), most likely using `hdiutil`
2. Construct a non-canonical string to be a filename (manually concatenating UTF-8 code points with some accents or something to that effect - perhaps look in detail at how HFS+ canonizes a string), and its canonical version
3. Create a file in the root of the mounted disk image with that name, ending in `.zip`
4. Attempt to construct a `UZKArchive` pointing to the zip file name above by the canonical name
5. (Maybe) List its contents

Step 5 might not be necessary if the APFS test fails on step 4.

**Comment by amosavian** [comment]
1. HFS+ uses form D. which effectively means `NSString.decomposedStringWithCanonicalMapping` and deleting a range of characters then. `fileSystemRepresentation` exactly do same to string in Darwin I think.

2. I think we should only handle to make canonical form of file name when **extracting**. Because doing this when compressing may cause problem in storing files with different normalization. For testing, we may have a prepared zip with files which names are saved with `precomposedStringWithCanonicalMapping` (default in linux) and check uncompressed file names to be equal with `fileSystemRepresentation`.

**Comment by abbeycode** [comment]
@amosavian I could use a hand with this. I've written the code to create an APFS image in the new FileSystemTests file (`apfs` branch). Can you help me make a case that fails there?

**Comment by amosavian** [comment]
why just not simply create a zip file in case-sensitive APFS with files which file names normalized using `precomposedStringWithCanonicalMapping` method for testing?

**Comment by abbeycode** [comment]
But if the filenames are normalized, then everything should already work correctly, right? Right now I'm trying to write a test case that reproduces the bug.

**Comment by amosavian** [comment]
Apple has included utf normalization to APFS in iOS 10.3.3 onwards, which I think make this case redundant as only iOS 10.3.0, 10.3.1 and 10.3.2 is affected.

**Comment by abbeycode** [comment]
@amosavian Thanks! I didn't see that

**Comment by amosavian** [comment]
@abbeycode This is what Apple says:

> In macOS High Sierra, APFS is normalization-insensitive in both the case-insensitive and case-sensitive variants, using a hash-based native normalization scheme. In iOS 11, APFS is normalization-insensitive as well, using either a native normalization scheme (erase restores only) or runtime normalization scheme (upgrades from previous versions). Runtime normalization will also be available in iOS 10.3.3 and macOS Sierra 10.12.6. Being normalization-insensitive ensures that normalization variants of a filename cannot be created in the same directory, and that a filename can be found with any of its normalization variants. This means that developers don’t need to do any additional work to ensure correct normalization behavior in these versions of macOS and iOS.

https://developer.apple.com/library/content/documentation/FileManagement/Conceptual/APFS_Guide/FAQ/FAQ.html
