### ISSUE TITLE
Crash when trying to extract password protected file in zip with wrong password

### ISSUE THREAD

**Issue by amosavian** [abbeycode/UnzipKit#56]
I get crash (EXC_BAD_ACCESS) when trying to extract password protected file with a wrong password:

```
UnzipKit error...
Name: Unknown error code: -3
Detail: Failed to read file Test File C.m4a in zip
```

Error line: https://github.com/abbeycode/UnzipKit/blob/master/Source/UZKArchive.m#L1355

**Comment by abbeycode** [comment]
Thanks for reporting this. Can you please take a look at [the issue template I created](https://github.com/abbeycode/UnzipKit/blob/master/.github/ISSUE_TEMPLATE.MD) and copy/paste into your issue? I could use the additional info requested there to figure out what's going on for you.

**Comment by amosavian** [comment]
**Step to reproduce:**
1- Open `Test Archive (Password).zip` inside Tests folder
2- Set password property to a wrong password e.g. `hello`
3 - Try to extract using `extractDataFromFile:progress:error:`

**Comment by abbeycode** [comment]
I've pushed a test case into a branch that follows the code you described, but with correct results. Can you please update the test case so it fails in the way you're expecting?

**Comment by amosavian** [comment]
I still have it. I don't know how to reproduce it in testcase. I will fix it when I find the issue thanks

**Comment by amosavian** [comment]
@abbeycode please try to extract that jpeg or mp4 file. Your code may try to extract `Test File A.txt` which has no problem! Problem is with files larger than 4096 bytes.

**Comment by amosavian** [comment]
I can confirm the problem is with assigning `innerError` object inside `@autoreleasepool` block. This code works without error:

```objective-c
- (BOOL)extractBufferedDataFromFile:(NSString *)filePath
                              error:(NSError * __autoreleasing*)error
                             action:(void (^)(NSData *, CGFloat))action
{
    NSUInteger bufferSize = 4096; //Arbitrary
    
    BOOL success = [self performActionWithArchiveOpen:^(NSError * __autoreleasing*innerError) {
        if (![self locateFileInZip:filePath error:innerError]) {
            [self assignError:innerError code:UZKErrorCodeFileNotFoundInArchive
                       detail:[NSString localizedStringWithFormat:NSLocalizedStringFromTableInBundle(@"Failed to locate '%@' in archive during buffered read", @"UnzipKit", _resources, @"Detailed error string"),
                               filePath]];
            return;
        }
        
        UZKFileInfo *info = [self currentFileInZipInfo:innerError];
        
        if (!info) {
            NSLog(@"Failed to locate file %@ in zip", filePath);
            return;
        }
        
        if (![self openFile:innerError]) {
            return;
        }
        
        long long bytesDecompressed = 0;
        
        int innerErr = 0;
        
        for (;;)
        {
            @autoreleasepool {
                NSMutableData *data = [NSMutableData dataWithLength:bufferSize];
                int bytesRead = unzReadCurrentFile(self.unzFile, data.mutableBytes, (unsigned)bufferSize);
                
                if (bytesRead <= 0) {
                    break;
                }
                
                data.length = bytesRead;
                bytesDecompressed += bytesRead;
                
                if (action) {
                    action([data copy], bytesDecompressed / (CGFloat)info.uncompressedSize);
                }
            }
        }
        
        if (innerErr < 0) {
            [self assignError:innerError code:innerErr
                       detail:[NSString localizedStringWithFormat:NSLocalizedStringFromTableInBundle(@"Failed to read file %@ in zip", @"UnzipKit", _resources, @"Detailed error string"),
                               info.filename]];
        }
        
        int err = unzCloseCurrentFile(self.unzFile);
        if (err != UNZ_OK) {
            if (err == UZKErrorCodeCRCError) {
                err = UZKErrorCodeInvalidPassword;
            }
            
            [self assignError:innerError code:err
                       detail:NSLocalizedStringFromTableInBundle(@"Error closing current file during buffered read", @"UnzipKit", _resources, @"Detailed error string")];
        }
        return;
    } inMode:UZKFileModeUnzip error:error];
    
    return success;
}
```

**Comment by amosavian** [comment]
Merge or my current pull request, I will fix them all myself

**Comment by abbeycode** [comment]
Are you still planning to fix this with a PR?

**Comment by abbeycode** [comment]
@amosavian I'm going through open issues now, so you'll see me replying to a bunch of them. Sorry to hit you all at once :)

Regarding this one, I'm not clear where we stand. I had created a branch (named [issue56](https://github.com/abbeycode/UnzipKit/tree/issue56)) with test cases that I thought would demonstrate the bug you're reporting, but they pass. Can you please clone that branch and demonstrate how you can reproduce the bug?

Also, you might have created a PR, but there aren't any open ones. If you help me with the test cases (you can open a PR to modify them so they fail and demonstrate the bug), I can incorporate the fix you proposed into another PR, since I've made a bunch of changes since then.

**Comment by amosavian** [comment]
How about continuing discussion in #51?
