### ISSUE TITLE
Integration with FilesProvider

### ISSUE THREAD

**Issue by amosavian** [abbeycode/UnzipKit#65]
This is not an issue.

I maintain a project [amosavian/FileProvider](https://github.com/amosavian/FileProvider) which allows to browse and do file operations async. I've used it in [my applications](https://itunes.apple.com/us/app/file-manager-pdf-reader-music-player/id1017809685?mt=8).

I've written some extenstions, based on your work, to allow users browse zip/rar files and treat them like normal folders. I can't have a dependency in my repo, but I put the code here to allow other to use them:

[ZipFileProvider](https://gist.github.com/amosavian/f59138c4c876609ca4044485d8f349e2)
[RarFileProvider](https://gist.github.com/amosavian/bf5c9f106dc31551c06e2d201c3cb878)

**Comment by abbeycode** [comment]
Looks cool, thanks for sharing!
