### ISSUE TITLE
How to build a fat binary for iOS and simulator?

### ISSUE THREAD

**Issue by brendand** [abbeycode/UnzipKit#72]
Hi,

I downloaded the latest 1.9 beta version and I wanted to build a fat binary for iOS and the simulator. What's the proper way to do that from within Xcode? I tried building and archive, but I don't get a fat binary.

**Comment by brendand** [comment]
Also, when I use the Archive command in Xcode and then export the product, I get libminizip.a as the only output. That's not the full UnzipKit.framework.

**Comment by abbeycode** [comment]
I pushed a change that should hopefully take care of `libminizip.a` showing up, but I'm not clear on what you're trying to accomplish. I would recommend using Carthage if you want a binary of the framework, or you can download a copy of the built framework from the release's page on GitHub ([an example](https://github.com/abbeycode/UnzipKit/releases/tag/1.9-beta3)).

Build and Archive, as far as I know, is intended for app targets, not frameworks.

**Comment by brendand** [comment]
I was just attempting to get a build that had bitcode support and a fat binary that I could deploy to the App Store. I knew that Archive would normally build with bitcode support. 

I managed to build with bitcode support AND fat binary AND stripping out the Intel parts for deployment. Took a while to figure it all out. I just hadn't run my app in the simulator in a while and a few frameworks I was using (including UnzipKit) wouldn't run in the simulator for me because I didn't have fat binaries of them.

I didn't realize you had pre-built binaries. That's great!

I don't use Carthage right now, so I just use Xcode to build frameworks.

**Comment by abbeycode** [comment]
Cool, it sounds like you're all set?

Also, that's what Carthage basically does, is checks out libraries from GitHub and builds with Xcode for you to manually integrate with your project (in contrast with CocoaPods, which integrates itself into your workspace and builds static libraries it integrates. FYI, the binaries attached to the GitHub releases are produced by Carthage as part of the automated build process.

**Comment by brendand** [comment]
Yup, I'm all set. Thanks!

I'll have to look into Carthage.
