### ISSUE TITLE
Bad CFBundleExecutable uploading to iTunes Connect

### ISSUE THREAD

**Issue by brendand** [abbeycode/UnzipKit#76]
Using the pre-built binary for 1.9, at the end of uploading to iTunes Connect, I get the following error in the Xcode organizer window:

> ERROR ITMS-90261: "Bad CFBundleExecutable. Cannot find executable file that matches the value of CFBundleExecutable in the nested bundle UnzipKitResources [.../Contents/Frameworks/UnzipKit.framework/Versions/A/Resources/UnzipKitResources.bundle] property list file."

I had to remove the `CFBundleExecutable` property from the `Info.plist` file in the UnzipKitResources.bundle to get it to upload properly.

**Comment by abbeycode** [comment]
Thanks for catching this one!

**Comment by brendand** [comment]
Thanks for fixing it!
