### ISSUE TITLE
Can't unzip large file ~6Gb

### ISSUE THREAD

**Issue by alexthgil** [abbeycode/UnzipKit#77]
Hello)
Im trying to use UnzipKit and I have a little issue. I have an zip archive with one large file about ~6Gb.  I have an error when I'm trying to unzip this file.
I think I found similar issue  

https://github.com/abbeycode/UnzipKit/issues/25

my code:
```
        do {
            let archive = try! UZKArchive(url: URL(fileURLWithPath: "/Users/alex/Desktop/A.zip"))
            let filesList = try archive.listFilenames()
            let filesInfoArchive = try archive.listFileInfo()
            try archive.extractFiles(to: "/Users/alex/Desktop/folder", overwrite: true, progress: nil)
            print(filesList)
        } catch let error as NSError {
            print("Exeption ...\(error)")
        }
```

Console:

`Error Domain=UZKErrorDomain Code=-103 "Bad zip file" UserInfo={NSLocalizedFailureReason=Bad zip file, NSUnderlyingError=0x60000025fb00 {Error Domain=UZKErrorDomain Code=-103 "Bad zip file" UserInfo={NSLocalizedFailureReason=Bad zip file, NSLocalizedRecoverySuggestion=Error opening archive (-103), NSURL=file:///Users/alex/Desktop/A.zip, NSLocalizedDescription=Bad zip file}}, NSLocalizedRecoverySuggestion=Bad zip file, NSURL=file:///Users/alex/Desktop/A.zip, NSLocalizedDescription=Bad zip file}`

Could you please provide some hint on this situation? Thanks)

**Comment by alexthgil** [comment]
I'm running on macOS.

**Comment by abbeycode** [comment]
How did you install, with CocoaPods? If so, you can try stepping through and looking at the line where it's failing. Also, which version of UnzipKit are you using? Are there multiple different files like that you're having problems with, or is it just this one? I'd offer to take a look and see what I can determine, but it's a little tough for you to send me a 6 GB file to look at it myself, though.

**Comment by alexthgil** [comment]
hello) Sorry for hight ping respond. 
Steps to reproduce:
1. Download linked file
2. Execute code from test project

I’m using ‘1.8.5’ on macOS 10.13. 
Simple test project
https://drive.google.com/open?id=1LzpytHWCBBm1c_ss1PkVYuMZzAxM8zqF
Test file
https://drive.google.com/open?id=1p3CRu-rj9n2eVOkxn-iOlNGF_bSUrq_B

Thanks)

**Comment by alexthgil** [comment]
Updated simple test project
https://drive.google.com/open?id=1_H_sisp4_L0D-erjSq1UurQdRr0s0PK8

**Comment by abbeycode** [comment]
@alexthgil That's super helpful, thanks! I'll take a look when I can

**Comment by abbeycode** [comment]
I am SO sorry it took me a year (_exactly a year, which is creepy_) to look at this. I largely work on open source projects when I'm away from reliable internet, and kept forgetting to download the file when I was.

I looked at it now, and I'm not sure the 6 GB file you sent is actually a zip format archive. Is there any app (or library) you've used to successfully extract it? I tried BetterZip without success. I also opened it up in a hex editor to look for the Zip format header at the beginning of every file, and didn't see one.

I'm going to close this as "works as designed", but please reopen it if you have additional info to help me solve it.
