### ISSUE TITLE
Compression methods is not working?

### ISSUE THREAD

**Issue by denis-ionov** [abbeycode/UnzipKit#79]
Trying write file to archive with compression method set (`UZKCompressionMethod.none`), but this file in the final archive still have **deflated** (`UZKCompressionMethod.default`) compression method.

Example code:
`let archive: UZKArchive = try! UZKArchive(url: url)`
`try! archive.write(data, filePath: path, fileDate: nil, compressionMethod: UZKCompressionMethod.none, password: nil, progress: nil)`

Then we can see compression method of file in archive: 
`archive.listFileInfo().first!.compressionMethod`
that will be `.default`, not `.none`

**Comment by abbeycode** [comment]
Thanks for noticing this, @denis-ionov. I don't change compression methods personally, but I'll write some test cases and see if this is a problem in the archival or in the listing.

**Comment by denis-ionov** [comment]
@abbeycode I found that problem is in the method implementation - Default compression method passed to next write function call, instead of compression method parameter. Fix this by using "next" write method with overwrite parameter.

**Comment by abbeycode** [comment]
Thanks for digging into it! I would welcome a pull request to address this, or else I'll fix it as soon as I have some availability.

**Comment by abbeycode** [comment]
I merged your pull request into the v1.9 branch. Thanks for the contribution!
