### ISSUE TITLE
Support for iOS 7 deployment target

### ISSUE THREAD

**Issue by K-Be** [abbeycode/UnzipKit#8]
You have ios deployment target in podspec is 8.0. Can you change it to ios 7.0?

**Comment by abbeycode** [comment]
I'm taking a look now - I'll let you know when I have something. I wouldn't want to open it up to a wider range without verifying it builds. I'm adding an iOS demo app that I can have Travis build, and fixing any compiler issues that turn up.

**Comment by abbeycode** [comment]
This has been addressed in v1.2.1, which I just released. Thanks for the suggestion!

**Comment by K-Be** [comment]
Thank you.
